;;;; ops.main.lisp

(in-package #:specops.x86)

;; Intel PDF pg. 588 has guide to opcode table abbreviations

(specops add (w op0 op1) *assembler-prototype-x86*
  ((:provisions
    (rex (determine-pfrex w op0 op1)) (modz0 (determine-modrm 0 op0))
    (sz? (determine-pfrsize w op0 op1 (of-program :exmode)))
    (mod10 (determine-modrm op1 op0)) (mod01 (determine-modrm op0 op1))
    (sib0 (determine-sib op0)) (sib1 (determine-sib op1)))
   (:priority                           0       2         1))
  ((    rex #x04                 op1 ) ((:w :b) (:gpr :a) (:imm)))
  ((sz? rex #x05            (w 2 op1)) ((:w :w) (:gpr :a) (:imm)))
  ((sz? rex #x05            (w 4 op1)) ((:w :d) (:gpr :a) (:imm)))
  ((    rex #x05            (w 4 op1)) ((:w :q) (:gpr :a) (:imm)))
  ;; ((           #x80 modz0 sib0      op1 ) ((:w :b) (:gxm   ) (:imm  )))
  ((    rex #x80 modz0 sib0      op1 ) ((:w :b) (:gxm   ) (:imm)))
  ((sz? rex #x81 modz0 sib0 (w 2 op1)) ((:w :w) (:gxm   ) (:imm)))
  ((sz? rex #x81 modz0 sib0 (w 4 op1)) ((:w :d) (:gxm   ) (:imm)))
  ((    rex #x81 modz0 sib0 (w 4 op1)) ((:w :q) (:gxm   ) (:imm)))
  ((sz? rex #x83 modz0 sib0      op1 ) ((:w :w) (:gxm   ) (:imm)))
  ((sz? rex #x83 modz0 sib0      op1 ) ((:w :d) (:gxm   ) (:imm)))
  ((    rex #x83 modz0 sib0      op1 ) ((:w :q) (:gxm   ) (:imm)))
  ;; ((           #x00 mod10 sib0          ) ((:w :b) (:gxm   ) (:gpr  )))
  ((    rex #x00 mod10 sib0          ) ((:w :b) (:gxm   ) (:gpr)))
  ((sz? rex #x01 mod10 sib0          ) ((:w :w) (:gxm   ) (:gpr)))
  ((sz? rex #x01 mod10 sib0          ) ((:w :d) (:gxm   ) (:gpr)))
  ((    rex #x01 mod10 sib0          ) ((:w :q) (:gxm   ) (:gpr)))
  ;; ((           #x02 mod01 sib1          ) ((:w :b) (:gpr   ) (:gxm  )))
  ((    rex #x02 mod01 sib1          ) ((:w :b) (:gpr   ) (:gxm)))
  ((sz? rex #x03 mod01 sib1          ) ((:w :w) (:gpr   ) (:gxm)))
  ((sz? rex #x03 mod01 sib1          ) ((:w :d) (:gpr   ) (:gxm)))
  ((    rex #x03 mod01 sib1          ) ((:w :q) (:gpr   ) (:gxm))))

(specops adc (w op0 op1) *assembler-prototype-x86*
  ((:provisions
    (rex (determine-pfrex w op0 op1)) (mod20 (determine-modrm 2 op0))
    (sz? (determine-pfrsize w op0 op1 (of-program :exmode)))
    (mod10 (determine-modrm op1 op0)) (mod01 (determine-modrm op0 op1))
    (sib0 (determine-sib op0)) (sib1 (determine-sib op1)))
   (:priority                           0       2         1))
  ((    rex #x14                 op1 ) ((:w :b) (:gpr :a) (:imm)))
  ((sz? rex #x15            (w 2 op1)) ((:w :w) (:gpr :a) (:imm)))
  ((sz? rex #x15            (w 4 op1)) ((:w :d) (:gpr :a) (:imm)))
  ((    rex #x15            (w 4 op1)) ((:w :q) (:gpr :a) (:imm)))
  ;; ((      #x80 mod20 sib0      op1 ) ((:gxm    8) (:imm)))
  ((    rex #x80 mod20 sib0      op1 ) ((:w :b) (:gxm   ) (:imm)))
  ((sz? rex #x81 mod20 sib0 (w 2 op1)) ((:w :w) (:gxm   ) (:imm)))
  ((sz? rex #x81 mod20 sib0 (w 4 op1)) ((:w :d) (:gxm   ) (:imm)))
  ((    rex #x81 mod20 sib0 (w 4 op1)) ((:w :q) (:gxm   ) (:imm)))
  ((sz? rex #x83 mod20 sib0      op1 ) ((:w :w) (:gxm   ) (:imm)))
  ((sz? rex #x83 mod20 sib0      op1 ) ((:w :d) (:gxm   ) (:imm)))
  ((    rex #x83 mod20 sib0      op1 ) ((:w :q) (:gxm   ) (:imm)))
  ;; ((      #x10 mod10 sib0          ) ((:gxm    8) (:gpr)))
  ((    rex #x10 mod10 sib0          ) ((:w :b) (:gxm   ) (:gpr)))
  ((sz? rex #x11 mod10 sib0          ) ((:w :w) (:gxm   ) (:gpr)))
  ((sz? rex #x11 mod10 sib0          ) ((:w :d) (:gxm   ) (:gpr)))
  ((    rex #x11 mod10 sib0          ) ((:w :q) (:gxm   ) (:gpr)))
  ;; ((      #x12 mod01 sib1          ) ((:gpr    8) (:gxm)))
  ((    rex #x12 mod01 sib1          ) ((:w :b) (:gpr   ) (:gxm)))
  ((sz? rex #x13 mod01 sib1          ) ((:w :w) (:gpr   ) (:gxm)))
  ((sz? rex #x13 mod01 sib1          ) ((:w :d) (:gpr   ) (:gxm)))
  ((    rex #x13 mod01 sib1          ) ((:w :q) (:gpr   ) (:gxm))))
